export const SET_STEPS = 'SET_STEPS';
export const INCREMENT_CURRENT_STEP = 'INCREMENT_CURRENT_STEP';
export const DECREMENT_CURRENT_STEP = 'DECREMENT_CURRENT_STEP';
export const SET_CURRENT_STEP = 'SET_CURRENT_STEP';
export const SET_DATA = 'SET_DATA';